### ISSUE TITLE
Getting an image from grapher

### ISSUE THREAD

**Issue by Adstram** [hemisemidemipresent/complex3#1]
little bugs in the program
1. When you click on the image button ,impossible to get a .png file !
2. impossible to modify the 3D limits for the graph

**Comment by Adstram** [comment]
![graph(9)](https://github.com/user-attachments/assets/12ec019f-832e-4eab-b479-b66d7dbd18f1)

**Comment by hemisemidemipresent** [comment]
Ah mb I overlooked this github issue

1. yea the image provided seems to not show the 3d surface, I looked into this a few years ago and didnt find a solution unfortunately, let me know if you have any ideas lol
2. I intended it to be such that if you wish to zoom in/out, you can use graph transformations to do that e.g. `sin(2z)` would zoom out by a factor of 2

**Comment by Adstram** [comment]
1. It is not necessary to put a button to make a screen printing: remove the photography button
2. What is important is to allow turning the 3D surface around Z axis.
3. What matter is also to add a North reference in order to get a 3D graph correctly positioned in a (O,x,y,z) referential.
4. A possibility to add a back ground image would be interesting.
[Complex Function GrapherTDV PUYUELO.pdf](https://github.com/user-attachments/files/17530345/Complex.Function.GrapherTDV.PUYUELO.pdf)
![M31_DSS_couleurs_RVB_deniveau_B_OK_ _TDV](https://github.com/user-attachments/assets/ba6ab08a-45ae-43aa-ad07-2b4fae02949b)

**Comment by hemisemidemipresent** [comment]
Assuming you mean that the z axis is the vertical axis, you can already rotate about that axis by dragging the screen
